// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.18.1
// source: backend/pkg/pluginapi/v1/control.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginControl_GetInfo_FullMethodName               = "/zboard.plugin.v1.PluginControl/GetInfo"
	PluginControl_Health_FullMethodName                = "/zboard.plugin.v1.PluginControl/Health"
	PluginControl_DescribeConfig_FullMethodName        = "/zboard.plugin.v1.PluginControl/DescribeConfig"
	PluginControl_ValidateConfig_FullMethodName        = "/zboard.plugin.v1.PluginControl/ValidateConfig"
	PluginControl_ApplyConfig_FullMethodName           = "/zboard.plugin.v1.PluginControl/ApplyConfig"
	PluginControl_TestConfig_FullMethodName            = "/zboard.plugin.v1.PluginControl/TestConfig"
	PluginControl_ListIdentityProviders_FullMethodName = "/zboard.plugin.v1.PluginControl/ListIdentityProviders"
	PluginControl_GetIdentityProvider_FullMethodName   = "/zboard.plugin.v1.PluginControl/GetIdentityProvider"
	PluginControl_ExchangeIdentity_FullMethodName      = "/zboard.plugin.v1.PluginControl/ExchangeIdentity"
)

// PluginControlClient is the client API for PluginControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// No generic host command, SQL, node or credential service is exposed here.
type PluginControlClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Info, error)
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResult, error)
	// Optional safe configuration projection; secrets must be omitted.
	DescribeConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResult, error)
	ValidateConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResult, error)
	ApplyConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*HealthResult, error)
	TestConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*HealthResult, error)
	// Requires zboard.identity.provider.v1. Host owns redirects, state and sessions.
	ListIdentityProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentityProviderList, error)
	GetIdentityProvider(ctx context.Context, in *IdentityProviderRequest, opts ...grpc.CallOption) (*IdentityProvider, error)
	ExchangeIdentity(ctx context.Context, in *IdentityExchange, opts ...grpc.CallOption) (*VerifiedIdentity, error)
}

type pluginControlClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginControlClient(cc grpc.ClientConnInterface) PluginControlClient {
	return &pluginControlClient{cc}
}

func (c *pluginControlClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Info, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Info)
	err := c.cc.Invoke(ctx, PluginControl_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResult)
	err := c.cc.Invoke(ctx, PluginControl_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) DescribeConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResult)
	err := c.cc.Invoke(ctx, PluginControl_DescribeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) ValidateConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResult)
	err := c.cc.Invoke(ctx, PluginControl_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) ApplyConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*HealthResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResult)
	err := c.cc.Invoke(ctx, PluginControl_ApplyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) TestConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*HealthResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResult)
	err := c.cc.Invoke(ctx, PluginControl_TestConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) ListIdentityProviders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IdentityProviderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityProviderList)
	err := c.cc.Invoke(ctx, PluginControl_ListIdentityProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) GetIdentityProvider(ctx context.Context, in *IdentityProviderRequest, opts ...grpc.CallOption) (*IdentityProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityProvider)
	err := c.cc.Invoke(ctx, PluginControl_GetIdentityProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) ExchangeIdentity(ctx context.Context, in *IdentityExchange, opts ...grpc.CallOption) (*VerifiedIdentity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifiedIdentity)
	err := c.cc.Invoke(ctx, PluginControl_ExchangeIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginControlServer is the server API for PluginControl service.
// All implementations must embed UnimplementedPluginControlServer
// for forward compatibility.
//
// No generic host command, SQL, node or credential service is exposed here.
type PluginControlServer interface {
	GetInfo(context.Context, *Empty) (*Info, error)
	Health(context.Context, *Empty) (*HealthResult, error)
	// Optional safe configuration projection; secrets must be omitted.
	DescribeConfig(context.Context, *ConfigRequest) (*ConfigResult, error)
	ValidateConfig(context.Context, *ConfigRequest) (*ConfigResult, error)
	ApplyConfig(context.Context, *ConfigRequest) (*HealthResult, error)
	TestConfig(context.Context, *ConfigRequest) (*HealthResult, error)
	// Requires zboard.identity.provider.v1. Host owns redirects, state and sessions.
	ListIdentityProviders(context.Context, *Empty) (*IdentityProviderList, error)
	GetIdentityProvider(context.Context, *IdentityProviderRequest) (*IdentityProvider, error)
	ExchangeIdentity(context.Context, *IdentityExchange) (*VerifiedIdentity, error)
	mustEmbedUnimplementedPluginControlServer()
}

// UnimplementedPluginControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginControlServer struct{}

func (UnimplementedPluginControlServer) GetInfo(context.Context, *Empty) (*Info, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPluginControlServer) Health(context.Context, *Empty) (*HealthResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginControlServer) DescribeConfig(context.Context, *ConfigRequest) (*ConfigResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeConfig not implemented")
}
func (UnimplementedPluginControlServer) ValidateConfig(context.Context, *ConfigRequest) (*ConfigResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedPluginControlServer) ApplyConfig(context.Context, *ConfigRequest) (*HealthResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyConfig not implemented")
}
func (UnimplementedPluginControlServer) TestConfig(context.Context, *ConfigRequest) (*HealthResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConfig not implemented")
}
func (UnimplementedPluginControlServer) ListIdentityProviders(context.Context, *Empty) (*IdentityProviderList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdentityProviders not implemented")
}
func (UnimplementedPluginControlServer) GetIdentityProvider(context.Context, *IdentityProviderRequest) (*IdentityProvider, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdentityProvider not implemented")
}
func (UnimplementedPluginControlServer) ExchangeIdentity(context.Context, *IdentityExchange) (*VerifiedIdentity, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeIdentity not implemented")
}
func (UnimplementedPluginControlServer) mustEmbedUnimplementedPluginControlServer() {}
func (UnimplementedPluginControlServer) testEmbeddedByValue()                       {}

// UnsafePluginControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginControlServer will
// result in compilation errors.
type UnsafePluginControlServer interface {
	mustEmbedUnimplementedPluginControlServer()
}

func RegisterPluginControlServer(s grpc.ServiceRegistrar, srv PluginControlServer) {
	// If the following call panics, it indicates UnimplementedPluginControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginControl_ServiceDesc, srv)
}

func _PluginControl_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_DescribeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).DescribeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_DescribeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).DescribeConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).ValidateConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_ApplyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).ApplyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_ApplyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).ApplyConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_TestConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).TestConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_TestConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).TestConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_ListIdentityProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).ListIdentityProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_ListIdentityProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).ListIdentityProviders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_GetIdentityProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).GetIdentityProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_GetIdentityProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).GetIdentityProvider(ctx, req.(*IdentityProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_ExchangeIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityExchange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).ExchangeIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_ExchangeIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).ExchangeIdentity(ctx, req.(*IdentityExchange))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginControl_ServiceDesc is the grpc.ServiceDesc for PluginControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zboard.plugin.v1.PluginControl",
	HandlerType: (*PluginControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PluginControl_GetInfo_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PluginControl_Health_Handler,
		},
		{
			MethodName: "DescribeConfig",
			Handler:    _PluginControl_DescribeConfig_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _PluginControl_ValidateConfig_Handler,
		},
		{
			MethodName: "ApplyConfig",
			Handler:    _PluginControl_ApplyConfig_Handler,
		},
		{
			MethodName: "TestConfig",
			Handler:    _PluginControl_TestConfig_Handler,
		},
		{
			MethodName: "ListIdentityProviders",
			Handler:    _PluginControl_ListIdentityProviders_Handler,
		},
		{
			MethodName: "GetIdentityProvider",
			Handler:    _PluginControl_GetIdentityProvider_Handler,
		},
		{
			MethodName: "ExchangeIdentity",
			Handler:    _PluginControl_ExchangeIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/pkg/pluginapi/v1/control.proto",
}
