<template>
  <section class="account-page stack"><header class="account-page-header"><div><p class="page-eyebrow">TRAFFIC</p><h1>流量明细</h1><p>查看总量、今日消耗和每条计费记录。</p></div><button class="button button-secondary" type="button" :disabled="loading" @click="load"><UiIcon name="refresh" />刷新</button></header><div v-if="error" class="alert alert-danger"><UiIcon name="alert" />{{ error }}</div>
    <div class="account-metric-grid"><article><span class="metric-icon"><UiIcon name="activity" /></span><div><small>剩余可用</small><strong>{{formatBytes(summary.remaining_bytes)}}</strong><p>当前有效订阅汇总</p></div></article><article><span class="metric-icon success"><UiIcon name="database" /></span><div><small>累计使用</small><strong>{{formatBytes(summary.total_used_bytes)}}</strong><p>历史计费流量</p></div></article><article><span class="metric-icon warning"><UiIcon name="clock" /></span><div><small>今日使用</small><strong>{{formatBytes(summary.used_bytes_today)}}</strong><p>{{formatDateTime(summary.as_of)}}</p></div></article></div>
    <article class="panel"><header class="panel-header"><div><h2>使用记录</h2><p>原始流量按套餐的流量方向策略选择后，仅应用协议端点倍率。</p></div><span class="count-label">{{records.length}} 条</span></header><div v-if="records.length" class="table-shell"><table class="data-table"><thead><tr><th>时间</th><th>订阅</th><th>上行</th><th>下行</th><th>端点倍率</th><th>计费流量</th></tr></thead><tbody><tr v-for="record in records" :key="record.id"><td>{{formatDateTime(record.occurred_at||record.created_at)}}</td><td>#{{record.subscription_id||'—'}}</td><td>{{formatBytes(record.upload_bytes)}}</td><td>{{formatBytes(record.download_bytes)}}</td><td>{{(record.protocol_multiplier_milli||1000)/1000}}×</td><td><strong>{{formatBytes(record.used_bytes)}}</strong></td></tr></tbody></table></div><EmptyState v-else icon="activity" title="还没有流量记录" description="节点开始上报使用量后，明细会显示在这里。" /></article>
    <aside class="account-notice"><UiIcon name="activity" /><div><strong>为什么计费流量可能不同？</strong><p>套餐可以按上行、下行或双向选择原始流量，随后只应用协议端点倍率；这里展示最终实际扣除量。</p></div></aside>
  </section>
</template>
<script setup lang="ts">
import{onMounted,ref}from'vue';import{fetchTrafficRecords,fetchTrafficSummary}from'../../api/client';import EmptyState from'../../components/EmptyState.vue';import UiIcon from'../../components/UiIcon.vue';import{formatBytes,formatDateTime}from'../../utils/format';const summary=ref<any>({});const records=ref<any[]>([]);const loading=ref(false);const error=ref('');async function load(){loading.value=true;error.value='';try{[summary.value,records.value]=await Promise.all([fetchTrafficSummary(),fetchTrafficRecords()])}catch(e:any){error.value=e?.response?.data?.message||'流量信息加载失败。'}finally{loading.value=false}}onMounted(load)
</script>
