<template>
  <section class="account-page stack"><header class="account-page-header"><div><p class="page-eyebrow">SUBSCRIPTION</p><h1>订阅配置</h1><p>查看有效服务，并管理客户端使用的专属订阅链接。</p></div><button class="button button-secondary" type="button" :disabled="loading" @click="load"><UiIcon name="refresh" />刷新</button></header><div v-if="message" class="alert alert-success"><UiIcon name="check" />{{ message }}</div><div v-if="error" class="alert alert-danger"><UiIcon name="alert" />{{ error }}</div>
    <div class="section-grid"><article class="panel span-7"><header class="panel-header"><div><h2>我的订阅</h2><p>只有有效且未耗尽流量的订阅会参与配置交付。</p></div><StatusBadge :tone="activeSubscriptions.length?'success':'neutral'">{{ activeSubscriptions.length }} 个有效</StatusBadge></header><div v-if="subscriptions.length" class="panel-body customer-subscriptions"><article v-for="sub in subscriptions" :key="sub.id"><div class="subscription-title"><div><span>订阅 #{{ sub.id }}</span><h3>{{ planName(sub.plan_id) }}</h3></div><StatusBadge :tone="subTone(sub.status)">{{ subLabel(sub.status) }}</StatusBadge></div><p class="quota-value">{{ formatBytes(Math.max(0,sub.flow_total-sub.flow_used)) }} <span>/ {{ formatBytes(sub.flow_total) }}</span></p><div class="usage-track"><i :style="{width:`${percent(sub)}%`}"></i></div><footer><span>到期 {{ formatDateTime(sub.end_at) }}</span><RouterLink class="button button-secondary button-sm" to="/account/plans">续费套餐</RouterLink></footer></article></div><EmptyState v-else icon="plans" title="暂无订阅" description="订单确认后，订阅会自动显示在这里。" /></article>
      <article class="panel span-5"><header class="panel-header"><div><h2>专属订阅链接</h2><p>将链接添加到受支持的客户端。</p></div><StatusBadge :tone="access.configured?'success':'warning'">{{access.configured?'已启用':'未生成'}}</StatusBadge></header><div class="panel-body access-panel"><span class="access-icon"><UiIcon name="key" /></span><div class="access-meta" v-if="access.configured"><strong>订阅凭证已启用</strong><p>凭证前缀 <code>{{ access.token_prefix }}…</code></p><p>最近使用：{{ formatDateTime(access.last_used_at) }}</p></div><div class="access-meta" v-else><strong>尚未生成订阅链接</strong><p>拥有有效订阅后再生成链接，可以直接导入客户端。</p></div><label v-if="subscriptionUrl" class="field access-url"><span>完整链接仅本次显示</span><input :value="subscriptionUrl" readonly /></label><div class="access-actions"><button v-if="subscriptionUrl" class="button button-secondary button-sm" type="button" @click="copy"><UiIcon name="copy" />{{ copyLabel }}</button><button class="button button-secondary button-sm" type="button" :disabled="!activeSubscriptions.length" @click="ask(access.configured?'rotate':'generate')">{{ access.configured?'轮换链接':'生成链接' }}</button><button v-if="access.configured" class="button button-danger button-sm" type="button" @click="ask('revoke')">吊销</button></div><p v-if="!activeSubscriptions.length" class="field-hint">需要先拥有有效订阅。</p></div></article></div>
    <aside class="account-notice"><UiIcon name="shield" /><div><strong>链接就是访问凭证</strong><p>不要发送到公开群组或截图分享。怀疑泄露时立即轮换，旧链接会马上失效。</p></div></aside>
    <ConfirmDialog :open="confirmOpen" :title="confirmTitle" :message="confirmMessage" :confirm-text="confirmText" :tone="kind==='revoke'?'danger':'primary'" :busy="working" @close="confirmOpen=false" @confirm="execute" />
  </section>
</template>
<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';import { fetchPlans,fetchSubscriptions,fetchSubscriptionAccess,revokeSubscriptionAccess,rotateSubscriptionAccess } from '../../api/client';import ConfirmDialog from '../../components/ConfirmDialog.vue';import EmptyState from '../../components/EmptyState.vue';import StatusBadge from '../../components/StatusBadge.vue';import UiIcon from '../../components/UiIcon.vue';import { formatBytes,formatDateTime } from '../../utils/format'
const subscriptions=ref<any[]>([]);const plans=ref<any[]>([]);const access=ref<any>({configured:false});const subscriptionUrl=ref('');const copyLabel=ref('复制链接');const loading=ref(false);const working=ref(false);const error=ref('');const message=ref('');const confirmOpen=ref(false);const kind=ref<'generate'|'rotate'|'revoke'>('generate')
const activeSubscriptions=computed(()=>subscriptions.value.filter(s=>s.status==='active'));const confirmTitle=computed(()=>kind.value==='generate'?'生成订阅链接？':kind.value==='rotate'?'轮换订阅链接？':'吊销订阅链接？');const confirmText=computed(()=>kind.value==='generate'?'生成链接':kind.value==='rotate'?'确认轮换':'确认吊销');const confirmMessage=computed(()=>kind.value==='generate'?'完整链接只显示一次，请立即复制到客户端。':kind.value==='rotate'?'旧链接会立即失效，已有客户端需要更新。':'吊销后所有客户端都无法继续拉取配置。')
function planName(id:number){return plans.value.find(p=>p.id===id)?.name||`套餐 #${id}`}function percent(s:any){return s.flow_total?Math.min(100,Math.round(s.flow_used/s.flow_total*100)):0}function subTone(s:string):'success'|'warning'|'danger'|'neutral'{return s==='active'?'success':s==='expired'?'warning':s==='exhausted'?'danger':'neutral'}function subLabel(s:string){return({active:'有效',expired:'已到期',exhausted:'流量耗尽',inactive:'无效'}as Record<string,string>)[s]||s}
async function load(){loading.value=true;error.value='';try{[subscriptions.value,plans.value,access.value]=await Promise.all([fetchSubscriptions(),fetchPlans(),fetchSubscriptionAccess()])}catch(e:any){error.value=e?.response?.data?.message||'订阅信息加载失败。'}finally{loading.value=false}}function ask(next:typeof kind.value){kind.value=next;confirmOpen.value=true}
async function execute(){working.value=true;error.value='';message.value='';try{if(kind.value==='revoke'){await revokeSubscriptionAccess();access.value={configured:false};subscriptionUrl.value='';message.value='订阅链接已吊销。'}else{const result=await rotateSubscriptionAccess();access.value=result;subscriptionUrl.value=`${window.location.origin}${result.subscription_url}`;copyLabel.value='复制链接';message.value=kind.value==='rotate'?'订阅链接已轮换，请立即复制新链接。':'订阅链接已生成，请立即复制。'}confirmOpen.value=false}catch(e:any){error.value=e?.response?.data?.message||'操作失败。'}finally{working.value=false}}
async function copy(){try{await navigator.clipboard.writeText(subscriptionUrl.value);copyLabel.value='已复制'}catch{copyLabel.value='复制失败'}}onMounted(load)
</script>
