<template>
  <section class="account-page stack"><header class="account-page-header"><div><p class="page-eyebrow">ORDERS</p><h1>我的订单</h1><p>查看商品快照、金额和处理进度。</p></div><RouterLink class="button" to="/account/plans"><UiIcon name="plus" />购买套餐</RouterLink></header><div v-if="message" class="alert alert-success"><UiIcon name="check" />{{ message }}</div><div v-if="error" class="alert alert-danger"><UiIcon name="alert" />{{ error }}</div>
    <article class="panel"><div class="panel-body toolbar"><div class="toolbar-group"><label class="field compact-field"><span>订单状态</span><select v-model="status" @change="load"><option value="">全部状态</option><option value="pending">待支付</option><option value="paid">已支付</option><option value="failed">失败</option><option value="canceled">已取消</option></select></label></div><span class="muted">共 {{ orders.length }} 条</span></div><div v-if="orders.length" class="table-shell"><table class="data-table"><thead><tr><th>订单</th><th>商品规格</th><th>金额</th><th>状态</th><th>时间</th><th></th></tr></thead><tbody><tr v-for="item in orders" :key="item.id"><td><div class="cell-title"><strong>#{{ item.id }}</strong><span class="mono">{{ item.trade_no }}</span></div></td><td><div class="cell-title"><strong>{{ item.plan_name||`套餐 #${item.plan_id}` }}</strong><span>{{ item.sku_name }}</span></div></td><td>{{ formatCurrency(item.amount_cents,item.currency) }}</td><td><StatusBadge :tone="tone(item.status)">{{ label(item.status) }}</StatusBadge></td><td>{{ formatDateTime(item.created_at) }}</td><td><div class="cell-actions"><button v-if="item.status==='pending'" class="button button-danger button-sm" type="button" @click="askCancel(item)">取消</button></div></td></tr></tbody></table></div><EmptyState v-else icon="billing" title="没有匹配订单" description="从套餐页面创建第一笔订单，或调整筛选条件。" /></article>
    <aside class="account-notice"><UiIcon name="clock" /><div><strong>当前采用人工确认流程</strong><p>订单创建后保持“待支付”状态，管理员确认收款后会自动生成订阅。用户端不会提供虚假的即时支付按钮。</p></div></aside>
    <ConfirmDialog :open="confirmOpen" title="取消这笔订单？" message="取消后无法继续处理，如需购买需要重新创建订单。" confirm-text="确认取消" tone="danger" :busy="canceling" @close="confirmOpen=false" @confirm="doCancel" />
  </section>
</template>
<script setup lang="ts">
import { onMounted,ref } from 'vue';import { cancelOrder,fetchOrders } from '../../api/client';import ConfirmDialog from '../../components/ConfirmDialog.vue';import EmptyState from '../../components/EmptyState.vue';import StatusBadge from '../../components/StatusBadge.vue';import UiIcon from '../../components/UiIcon.vue';import { formatCurrency,formatDateTime } from '../../utils/format'
const orders=ref<any[]>([]);const status=ref('');const error=ref('');const message=ref('');const confirmOpen=ref(false);const canceling=ref(false);const target=ref<any>(null)
function tone(s:string):'success'|'warning'|'danger'|'neutral'{return s==='paid'?'success':s==='pending'?'warning':s==='failed'?'danger':'neutral'}function label(s:string){return({pending:'待支付',paid:'已支付',failed:'失败',canceled:'已取消'}as Record<string,string>)[s]||s}
async function load(){error.value='';try{orders.value=await fetchOrders({status:status.value||undefined})}catch(e:any){error.value=e?.response?.data?.message||'订单加载失败。'}}function askCancel(item:any){target.value=item;confirmOpen.value=true}async function doCancel(){if(!target.value)return;canceling.value=true;try{await cancelOrder(target.value.id);confirmOpen.value=false;message.value='订单已取消。';await load()}catch(e:any){error.value=e?.response?.data?.message||'订单取消失败。'}finally{canceling.value=false}}
onMounted(load)
</script>
