worker_processes  auto;
events {
  worker_connections 1024;
}

http {
  upstream zboard_upstream {
    server zboard-blue:8080;
  }

  server {
    listen 80;
    location ~ ^/api/v1/nodes/[0-9]+/kernel/upload$ {
      client_max_body_size 129m;
      client_body_timeout 180s;
      proxy_request_buffering off;
      proxy_read_timeout 190s;
      proxy_send_timeout 190s;
      proxy_pass http://zboard_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location = /api/v1/files {
      client_max_body_size 6m;
      client_body_timeout 60s;
      proxy_request_buffering off;
      proxy_read_timeout 70s;
      proxy_send_timeout 70s;
      proxy_pass http://zboard_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location / {
      proxy_pass http://zboard_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
