worker_processes  auto;
events {
  worker_connections 1024;
}

http {
  upstream zboard_upstream {
    server zboard-blue:8080;
  }

  server {
    listen 80;
    location / {
      proxy_pass http://zboard_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
