-- zboard v0.0.1 pre-release schema baseline.
-- Development migrations 0001-0032 were squashed before the first public release.
-- Existing v0.0.1 databases must already have the original 0001 migration recorded.
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `audit_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned DEFAULT NULL,
  `actor` varchar(128) NOT NULL,
  `action` varchar(128) NOT NULL,
  `target` varchar(128) NOT NULL,
  `detail` text,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_audit_actor` (`actor`),
  KEY `idx_audit_created` (`created_at`),
  KEY `fk_audit_user` (`user_id`),
  KEY `idx_audit_logs_history_cursor` (`created_at`,`id`),
  CONSTRAINT `fk_audit_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `flow_usages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` bigint unsigned NOT NULL,
  `flow_id` varchar(128) NOT NULL,
  `protocol_credential_id` bigint unsigned NOT NULL,
  `subscription_id` bigint unsigned NOT NULL,
  `protocol_endpoint_id` bigint unsigned NOT NULL,
  `principal_key` varchar(128) NOT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '0',
  `raw_bytes` bigint NOT NULL DEFAULT '0',
  `upload_bytes` bigint NOT NULL DEFAULT '0',
  `download_bytes` bigint NOT NULL DEFAULT '0',
  `used_bytes` bigint NOT NULL DEFAULT '0',
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `last_event_id` varchar(191) NOT NULL,
  `last_seen_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_flow_usage_node_flow` (`node_id`,`flow_id`),
  KEY `idx_flow_usages_credential` (`protocol_credential_id`),
  KEY `idx_flow_usages_subscription` (`subscription_id`),
  KEY `idx_flow_usages_endpoint` (`protocol_endpoint_id`),
  KEY `idx_flow_usages_principal` (`principal_key`),
  KEY `idx_flow_usages_status_seen` (`status`,`last_seen_at`),
  CONSTRAINT `fk_flow_usages_credential` FOREIGN KEY (`protocol_credential_id`) REFERENCES `protocol_credentials` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_flow_usages_endpoint` FOREIGN KEY (`protocol_endpoint_id`) REFERENCES `protocol_endpoints` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_flow_usages_node` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_flow_usages_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `installations` (
  `id` bigint unsigned NOT NULL,
  `site_name` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `site_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `allow_registration` tinyint(1) NOT NULL DEFAULT '1',
  `installed_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `node_group_endpoints` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_group_id` bigint unsigned NOT NULL,
  `protocol_endpoint_id` bigint unsigned NOT NULL,
  `sort_order` int NOT NULL DEFAULT '0',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_node_group_endpoint` (`node_group_id`,`protocol_endpoint_id`),
  KEY `idx_node_group_endpoint_endpoint` (`protocol_endpoint_id`),
  CONSTRAINT `fk_node_group_endpoint_endpoint` FOREIGN KEY (`protocol_endpoint_id`) REFERENCES `protocol_endpoints` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_node_group_endpoint_group` FOREIGN KEY (`node_group_id`) REFERENCES `node_groups` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `node_groups` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `code` varchar(80) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_node_groups_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `node_kernel_states` (
  `node_id` bigint unsigned NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'unknown',
  `phase` varchar(32) NOT NULL DEFAULT 'idle',
  `recommended_action` varchar(24) NOT NULL DEFAULT 'detect',
  `platform_os` varchar(64) NOT NULL DEFAULT '',
  `architecture` varchar(32) NOT NULL DEFAULT '',
  `libc` varchar(64) NOT NULL DEFAULT '',
  `desired_version` varchar(64) NOT NULL DEFAULT '',
  `installed_version` varchar(64) NOT NULL DEFAULT '',
  `desired_sha256` char(64) NOT NULL DEFAULT '',
  `installed_sha256` char(64) NOT NULL DEFAULT '',
  `desired_config_sha256` char(64) NOT NULL DEFAULT '',
  `applied_config_sha256` char(64) NOT NULL DEFAULT '',
  `service_status` varchar(24) NOT NULL DEFAULT 'unknown',
  `control_status` varchar(24) NOT NULL DEFAULT 'unknown',
  `last_error` text NOT NULL,
  `active_operation_id` bigint unsigned DEFAULT NULL,
  `last_detected_at` datetime(3) DEFAULT NULL,
  `last_healthy_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`node_id`),
  KEY `idx_node_kernel_states_active_operation` (`active_operation_id`),
  CONSTRAINT `fk_node_kernel_states_node` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `node_operations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` bigint unsigned NOT NULL,
  `operation_type` varchar(24) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'running',
  `phase` varchar(32) NOT NULL DEFAULT 'queued',
  `requested_by` bigint unsigned NOT NULL,
  `desired_version` varchar(64) NOT NULL DEFAULT '',
  `desired_sha256` char(64) NOT NULL DEFAULT '',
  `artifact_url` varchar(512) NOT NULL DEFAULT '',
  `result_summary` text NOT NULL,
  `error` text NOT NULL,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_node_operations_node_created` (`node_id`,`created_at`),
  KEY `idx_node_operations_status` (`status`),
  KEY `fk_node_operations_requester` (`requested_by`),
  KEY `idx_node_operations_history_cursor` (`created_at`,`id`),
  CONSTRAINT `fk_node_operations_node` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_node_operations_requester` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `nodes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `region` varchar(32) NOT NULL,
  `address` varchar(128) NOT NULL,
  `node_credential` text,
  `node_credential_prefix` varchar(12) DEFAULT NULL,
  `node_credential_revoked_at` datetime(3) DEFAULT NULL,
  `communication_protocol` smallint NOT NULL DEFAULT '1',
  `status` smallint NOT NULL DEFAULT '0',
  `lifecycle_status` varchar(20) NOT NULL DEFAULT 'active',
  `config` json DEFAULT NULL,
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `is_online` tinyint(1) NOT NULL DEFAULT '0',
  `last_seen_at` datetime(3) DEFAULT NULL,
  `last_sync_at` datetime(3) DEFAULT NULL,
  `version` varchar(64) NOT NULL DEFAULT '',
  `ssh_host` varchar(64) DEFAULT NULL,
  `ssh_port` int NOT NULL DEFAULT '22',
  `ssh_user` varchar(64) DEFAULT NULL,
  `ssh_auth_method` varchar(20) NOT NULL DEFAULT 'password',
  `ssh_pwd` text,
  `ssh_private_key_passphrase` text,
  `ssh_privilege_mode` varchar(16) NOT NULL DEFAULT 'none',
  `ssh_privilege_password` text,
  `ssh_host_key_fingerprint` varchar(128) DEFAULT NULL,
  `ssh_verified_at` datetime(3) DEFAULT NULL,
  `connector_last_seen_at` datetime(3) DEFAULT NULL,
  `uptime_seconds` bigint unsigned NOT NULL DEFAULT '0',
  `active_flows` bigint unsigned NOT NULL DEFAULT '0',
  `bytes_up` bigint unsigned NOT NULL DEFAULT '0',
  `bytes_down` bigint unsigned NOT NULL DEFAULT '0',
  `traffic_secret` text,
  `traffic_secret_prefix` varchar(12) DEFAULT NULL,
  `traffic_secret_revoked_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `idx_nodes_connector_last_seen` (`connector_last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `managed_certificates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` bigint unsigned NOT NULL,
  `name` varchar(80) NOT NULL,
  `domains` json NOT NULL,
  `contact_email` varchar(254) NOT NULL,
  `environment` varchar(16) NOT NULL DEFAULT 'production',
  `challenge_type` varchar(16) NOT NULL DEFAULT 'http-01',
  `status` varchar(24) NOT NULL DEFAULT 'pending',
  `cert_path` varchar(255) NOT NULL DEFAULT '',
  `key_path` varchar(255) NOT NULL DEFAULT '',
  `serial_number` varchar(128) NOT NULL DEFAULT '',
  `fingerprint_sha256` char(64) NOT NULL DEFAULT '',
  `not_before` datetime(3) DEFAULT NULL,
  `not_after` datetime(3) DEFAULT NULL,
  `last_issued_at` datetime(3) DEFAULT NULL,
  `last_renewal_attempt_at` datetime(3) DEFAULT NULL,
  `next_renewal_at` datetime(3) DEFAULT NULL,
  `auto_renew` tinyint(1) NOT NULL DEFAULT '1',
  `renew_before_days` int NOT NULL DEFAULT '30',
  `last_error` text NOT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_managed_certificates_node` (`node_id`),
  KEY `idx_managed_certificates_status` (`status`),
  KEY `idx_managed_certificates_not_after` (`not_after`),
  KEY `idx_managed_certificates_next_renewal` (`next_renewal_at`),
  CONSTRAINT `fk_managed_certificates_node` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `certificate_operations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `managed_certificate_id` bigint unsigned NOT NULL,
  `node_id` bigint unsigned NOT NULL,
  `operation_type` varchar(16) NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'running',
  `phase` varchar(32) NOT NULL DEFAULT 'queued',
  `requested_by` bigint unsigned DEFAULT NULL,
  `result_summary` text NOT NULL,
  `error` text NOT NULL,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_certificate_operations_certificate` (`managed_certificate_id`,`created_at`),
  KEY `idx_certificate_operations_node` (`node_id`,`created_at`),
  KEY `idx_certificate_operations_status` (`status`),
  KEY `fk_certificate_operations_requester` (`requested_by`),
  CONSTRAINT `fk_certificate_operations_certificate` FOREIGN KEY (`managed_certificate_id`) REFERENCES `managed_certificates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_certificate_operations_node` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_certificate_operations_requester` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `plan_id` bigint unsigned DEFAULT NULL,
  `plan_sku_id` bigint unsigned NOT NULL,
  `subscription_id` bigint unsigned DEFAULT NULL,
  `target_subscription_id` bigint unsigned DEFAULT NULL,
  `trade_no` varchar(64) NOT NULL,
  `order_type` varchar(20) NOT NULL DEFAULT 'new',
  `amount_cents` bigint NOT NULL,
  `payable_amount` bigint NOT NULL DEFAULT '0',
  `paid_amount` bigint NOT NULL DEFAULT '0',
  `refund_amount` bigint NOT NULL DEFAULT '0',
  `discount_amount` bigint NOT NULL DEFAULT '0',
  `currency` varchar(16) NOT NULL DEFAULT 'USD',
  `channel` varchar(32) NOT NULL,
  `provider_trade_no` varchar(128) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `plan_name` varchar(80) NOT NULL DEFAULT '',
  `sku_name` varchar(80) NOT NULL DEFAULT '',
  `billing_unit` varchar(16) NOT NULL DEFAULT '',
  `billing_value` int NOT NULL DEFAULT '0',
  `traffic_bytes` bigint NOT NULL DEFAULT '0',
  `device_limit` int NOT NULL DEFAULT '0',
  `speed_limit_mbps` int NOT NULL DEFAULT '0',
  `raw_callback` text,
  `paid_at` datetime(3) DEFAULT NULL,
  `canceled_at` datetime(3) DEFAULT NULL,
  `fulfilled_at` datetime(3) DEFAULT NULL,
  `refunded_at` datetime(3) DEFAULT NULL,
  `failure_reason` varchar(255) NOT NULL DEFAULT '',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `trade_no` (`trade_no`),
  UNIQUE KEY `uk_orders_provider_trade_no` (`provider_trade_no`),
  KEY `idx_order_user` (`user_id`),
  KEY `idx_order_plan` (`plan_id`),
  KEY `idx_orders_plan_sku` (`plan_sku_id`),
  KEY `idx_orders_target_subscription` (`target_subscription_id`),
  KEY `idx_orders_created_at_id` (`created_at`,`id`),
  CONSTRAINT `fk_order_plan` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_order_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_orders_plan_sku` FOREIGN KEY (`plan_sku_id`) REFERENCES `plan_skus` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_orders_target_subscription` FOREIGN KEY (`target_subscription_id`) REFERENCES `subscriptions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `payment_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL,
  `provider` varchar(32) NOT NULL,
  `provider_event_id` varchar(128) NOT NULL,
  `event_type` varchar(32) NOT NULL,
  `amount_minor` bigint NOT NULL DEFAULT '0',
  `signature_valid` tinyint(1) NOT NULL DEFAULT '0',
  `payload` json DEFAULT NULL,
  `processed_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_payment_provider_event` (`provider`,`provider_event_id`),
  KEY `idx_payment_events_order` (`order_id`),
  CONSTRAINT `fk_payment_events_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `plan_skus` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_id` bigint unsigned NOT NULL,
  `code` varchar(80) NOT NULL,
  `name` varchar(80) NOT NULL,
  `sku_type` varchar(20) NOT NULL DEFAULT 'new',
  `billing_unit` varchar(16) NOT NULL,
  `billing_value` int NOT NULL,
  `price_cents` bigint NOT NULL,
  `currency` varchar(8) NOT NULL,
  `traffic_bytes` bigint NOT NULL,
  `device_limit` int NOT NULL,
  `speed_limit_mbps` int NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `sort_order` int NOT NULL DEFAULT '0',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_skus_code` (`code`),
  KEY `idx_plan_skus_plan` (`plan_id`),
  CONSTRAINT `fk_plan_skus_plan` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `plans` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `slug` varchar(80) NOT NULL,
  `summary` varchar(255) NOT NULL DEFAULT '',
  `description` text,
  `node_group_id` bigint unsigned NOT NULL,
  `traffic_bytes` bigint NOT NULL DEFAULT '0',
  `speed_limit_mbps` int NOT NULL DEFAULT '0',
  `max_active_subscriptions` int NOT NULL DEFAULT '0',
  `is_renewable` tinyint(1) NOT NULL DEFAULT '1',
  `device_limit` int NOT NULL DEFAULT '1',
  `family_limit` int NOT NULL DEFAULT '0',
  `reset_policy` smallint NOT NULL DEFAULT '0',
  `traffic_calc_mode` smallint NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `sort_order` int NOT NULL DEFAULT '0',
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `uk_plans_slug` (`slug`),
  KEY `idx_plans_node_group` (`node_group_id`),
  CONSTRAINT `fk_plans_node_group` FOREIGN KEY (`node_group_id`) REFERENCES `node_groups` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `protocol_credentials` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `subscription_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `protocol_endpoint_id` bigint unsigned NOT NULL,
  `node_id` bigint unsigned NOT NULL,
  `credential_id` varchar(96) NOT NULL,
  `principal_key` varchar(128) NOT NULL,
  `secret` text NOT NULL,
  `listen_port` int NOT NULL,
  `public_port` int NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `expires_at` datetime(3) NOT NULL,
  `last_used_at` datetime(3) DEFAULT NULL,
  `revoked_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_protocol_credential_subscription_endpoint` (`subscription_id`,`protocol_endpoint_id`),
  UNIQUE KEY `ux_protocol_credentials_credential_id` (`credential_id`),
  UNIQUE KEY `ux_protocol_credentials_principal_key` (`principal_key`),
  KEY `idx_protocol_credentials_user` (`user_id`,`status`),
  KEY `idx_protocol_credentials_node` (`node_id`,`status`),
  KEY `idx_protocol_credentials_endpoint` (`protocol_endpoint_id`,`status`),
  KEY `idx_protocol_credentials_expires` (`expires_at`),
  CONSTRAINT `fk_protocol_credentials_endpoint` FOREIGN KEY (`protocol_endpoint_id`) REFERENCES `protocol_endpoints` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_protocol_credentials_node` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_protocol_credentials_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_protocol_credentials_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `protocol_deployments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `protocol_endpoint_id` bigint unsigned NOT NULL,
  `node_id` bigint unsigned NOT NULL,
  `config_revision` bigint unsigned NOT NULL,
  `desired_config_sha256` char(64) NOT NULL DEFAULT '',
  `applied_config_sha256` char(64) NOT NULL DEFAULT '',
  `status` varchar(20) NOT NULL,
  `requested_by` bigint unsigned DEFAULT NULL,
  `output` text,
  `error` text,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_protocol_deployments_endpoint` (`protocol_endpoint_id`,`config_revision`),
  KEY `idx_protocol_deployments_node` (`node_id`,`status`),
  KEY `fk_protocol_deployments_user` (`requested_by`),
  KEY `idx_protocol_deployments_history_cursor` (`created_at`,`id`),
  CONSTRAINT `fk_protocol_deployments_endpoint` FOREIGN KEY (`protocol_endpoint_id`) REFERENCES `protocol_endpoints` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_protocol_deployments_node` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_protocol_deployments_user` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `protocol_endpoints` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `node_id` bigint unsigned NOT NULL,
  `name` varchar(80) NOT NULL,
  `runtime_key` varchar(36) NOT NULL,
  `protocol` varchar(32) NOT NULL,
  `address` varchar(255) NOT NULL,
  `port` int NOT NULL,
  `public_port` int NOT NULL DEFAULT '0',
  `cipher` smallint NOT NULL DEFAULT '0',
  `parent_protocol_id` bigint unsigned DEFAULT NULL,
  `multiplier_milli` bigint NOT NULL DEFAULT '1000',
  `server_config` text,
  `client_config` text,
  `optional_config` json DEFAULT NULL,
  `tags` json DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `sort_order` int NOT NULL DEFAULT '0',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_protocol_endpoints_runtime_key` (`runtime_key`),
  KEY `idx_protocol_endpoints_node` (`node_id`),
  KEY `idx_protocol_parent` (`parent_protocol_id`),
  CONSTRAINT `fk_protocol_endpoints_node` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_protocol_parent` FOREIGN KEY (`parent_protocol_id`) REFERENCES `protocol_endpoints` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `certificate_protocol_endpoints` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `managed_certificate_id` bigint unsigned NOT NULL,
  `protocol_endpoint_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_certificate_endpoint` (`managed_certificate_id`,`protocol_endpoint_id`),
  UNIQUE KEY `uk_certificate_protocol_endpoint` (`protocol_endpoint_id`),
  KEY `idx_certificate_endpoint_certificate` (`managed_certificate_id`),
  CONSTRAINT `fk_certificate_endpoint_certificate` FOREIGN KEY (`managed_certificate_id`) REFERENCES `managed_certificates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_certificate_endpoint_protocol` FOREIGN KEY (`protocol_endpoint_id`) REFERENCES `protocol_endpoints` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `quota_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `subscription_id` bigint unsigned NOT NULL,
  `event_type` varchar(24) NOT NULL,
  `delta_bytes` bigint NOT NULL,
  `balance_before` bigint NOT NULL,
  `balance_after` bigint NOT NULL,
  `reference_type` varchar(32) NOT NULL,
  `reference_id` varchar(128) NOT NULL,
  `detail` json DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_quota_event_reference` (`subscription_id`,`event_type`,`reference_type`,`reference_id`),
  KEY `idx_quota_events_subscription` (`subscription_id`,`created_at`),
  CONSTRAINT `fk_quota_events_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `subscription_members` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `subscription_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `member_role` varchar(16) NOT NULL DEFAULT 'member',
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `joined_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `removed_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_subscription_member` (`subscription_id`,`user_id`),
  KEY `idx_subscription_members_user` (`user_id`),
  CONSTRAINT `fk_subscription_members_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_subscription_members_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `subscription_rule_sets` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `renderer` varchar(32) NOT NULL,
  `tag` varchar(64) NOT NULL,
  `url` varchar(2048) NOT NULL,
  `behavior` varchar(16) NOT NULL DEFAULT '',
  `format` varchar(32) NOT NULL,
  `interval` int unsigned NOT NULL DEFAULT '86400',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_subscription_rule_set_renderer_tag` (`renderer`,`tag`),
  KEY `idx_subscription_rule_sets_renderer` (`renderer`),
  KEY `idx_subscription_rule_sets_is_active` (`is_active`),
  KEY `idx_subscription_rule_sets_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `subscription_template_rule_set_bindings` (
  `subscription_template_id` bigint unsigned NOT NULL,
  `subscription_rule_set_id` bigint unsigned NOT NULL,
  `action` varchar(96) NOT NULL,
  `position` int unsigned NOT NULL,
  PRIMARY KEY (`subscription_template_id`,`subscription_rule_set_id`),
  UNIQUE KEY `ux_subscription_template_rule_set_position` (`subscription_template_id`,`position`),
  KEY `idx_subscription_template_rule_set_bindings_rule_set` (`subscription_rule_set_id`),
  CONSTRAINT `fk_subscription_template_rule_set_library` FOREIGN KEY (`subscription_rule_set_id`) REFERENCES `subscription_rule_sets` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_subscription_template_rule_set_template` FOREIGN KEY (`subscription_template_id`) REFERENCES `subscription_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `subscription_templates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(80) NOT NULL,
  `slug` varchar(80) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `renderer` varchar(32) NOT NULL,
  `customization` json NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `sort_order` int NOT NULL DEFAULT '0',
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_subscription_templates_slug` (`slug`),
  KEY `idx_subscription_templates_active_sort` (`is_active`,`sort_order`),
  KEY `idx_subscription_templates_renderer` (`renderer`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `subscription_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `subscription_id` bigint unsigned DEFAULT NULL,
  `token_hash` varchar(64) NOT NULL,
  `token_ciphertext` text,
  `token_prefix` varchar(12) NOT NULL,
  `last_used_at` datetime(3) DEFAULT NULL,
  `revoked_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_subscription_token_user` (`user_id`),
  UNIQUE KEY `uq_subscription_token_hash` (`token_hash`),
  KEY `idx_subscription_tokens_subscription` (`subscription_id`),
  CONSTRAINT `fk_subscription_token_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_subscription_tokens_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `subscriptions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `plan_id` bigint unsigned NOT NULL,
  `plan_sku_id` bigint unsigned NOT NULL,
  `node_group_id` bigint unsigned NOT NULL,
  `subscription_type` smallint NOT NULL DEFAULT '1',
  `start_at` datetime(3) NOT NULL,
  `end_at` datetime(3) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `flow_total` bigint NOT NULL DEFAULT '0',
  `flow_used` bigint NOT NULL DEFAULT '0',
  `speed_limit_mbps` int NOT NULL DEFAULT '0',
  `device_limit` int NOT NULL DEFAULT '1',
  `family_limit` int NOT NULL DEFAULT '0',
  `renewal_price_minor` bigint NOT NULL DEFAULT '0',
  `reset_policy` smallint NOT NULL DEFAULT '0',
  `next_reset_at` datetime(3) DEFAULT NULL,
  `traffic_calc_mode` smallint NOT NULL DEFAULT '0',
  `config` json DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_plan` (`plan_id`),
  KEY `idx_subscriptions_plan_sku` (`plan_sku_id`),
  KEY `idx_subscriptions_reset` (`next_reset_at`),
  KEY `idx_subscriptions_node_group` (`node_group_id`),
  KEY `idx_subscriptions_end_at_id` (`end_at`,`id`),
  CONSTRAINT `fk_sub_plan` FOREIGN KEY (`plan_id`) REFERENCES `plans` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_sub_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_subscriptions_node_group` FOREIGN KEY (`node_group_id`) REFERENCES `node_groups` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_subscriptions_plan_sku` FOREIGN KEY (`plan_sku_id`) REFERENCES `plan_skus` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `system_configs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `config_key` varchar(80) NOT NULL,
  `name` varchar(120) NOT NULL,
  `value` text,
  `value_type` varchar(16) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `is_public` tinyint(1) NOT NULL DEFAULT '0',
  `is_secret` tinyint(1) NOT NULL DEFAULT '0',
  `revision` bigint unsigned NOT NULL DEFAULT '1',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_system_configs_key` (`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `task_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `task_id` bigint unsigned NOT NULL,
  `target_type` varchar(32) NOT NULL,
  `target_id` varchar(128) NOT NULL,
  `payload` json DEFAULT NULL,
  `status` smallint NOT NULL DEFAULT '0',
  `attempts` int NOT NULL DEFAULT '0',
  `error` text,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_task_target` (`task_id`,`target_type`,`target_id`),
  KEY `idx_task_items_status` (`task_id`,`status`),
  CONSTRAINT `fk_task_items_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(32) NOT NULL,
  `scope` json DEFAULT NULL,
  `content` json DEFAULT NULL,
  `status` smallint NOT NULL DEFAULT '0',
  `errors` text,
  `total` bigint NOT NULL DEFAULT '0',
  `current` bigint NOT NULL DEFAULT '0',
  `idempotency_key` varchar(128) DEFAULT NULL,
  `priority` int NOT NULL DEFAULT '0',
  `scheduled_at` datetime(3) DEFAULT NULL,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `attempts` int NOT NULL DEFAULT '0',
  `max_attempts` int NOT NULL DEFAULT '3',
  `locked_by` varchar(128) DEFAULT NULL,
  `locked_until` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tasks_idempotency` (`idempotency_key`),
  KEY `idx_tasks_dispatch` (`status`,`scheduled_at`,`priority`),
  KEY `idx_tasks_lock` (`locked_until`),
  KEY `idx_tasks_history_cursor` (`created_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ticket_messages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ticket_id` bigint unsigned NOT NULL,
  `author_id` bigint unsigned DEFAULT NULL,
  `author_role` varchar(16) NOT NULL,
  `message_type` varchar(16) NOT NULL,
  `body` text NOT NULL,
  `from_status` varchar(24) NOT NULL DEFAULT '',
  `to_status` varchar(24) NOT NULL DEFAULT '',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ticket_messages_ticket_time` (`ticket_id`,`created_at`,`id`),
  KEY `idx_ticket_messages_author` (`author_id`),
  CONSTRAINT `fk_ticket_messages_author` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_ticket_messages_ticket` FOREIGN KEY (`ticket_id`) REFERENCES `tickets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tickets` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ticket_no` varchar(32) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `subject` varchar(160) NOT NULL,
  `category` varchar(32) NOT NULL,
  `priority` smallint NOT NULL DEFAULT '1',
  `status` varchar(24) NOT NULL DEFAULT 'open',
  `last_message_at` datetime(3) NOT NULL,
  `resolved_at` datetime(3) DEFAULT NULL,
  `closed_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tickets_ticket_no` (`ticket_no`),
  KEY `idx_tickets_user_status` (`user_id`,`status`),
  KEY `idx_tickets_queue` (`status`,`priority`,`last_message_at`),
  KEY `idx_tickets_category` (`category`),
  CONSTRAINT `fk_tickets_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `traffic_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned DEFAULT NULL,
  `subscription_id` bigint unsigned DEFAULT NULL,
  `node_id` bigint unsigned DEFAULT NULL,
  `protocol_endpoint_id` bigint unsigned DEFAULT NULL,
  `report_id` varchar(191) DEFAULT NULL,
  `flow_id` varchar(128) NOT NULL DEFAULT '',
  `event_type` varchar(32) NOT NULL DEFAULT '',
  `event_revision` bigint unsigned NOT NULL DEFAULT '0',
  `nonce` varchar(64) DEFAULT NULL,
  `raw_bytes` bigint NOT NULL DEFAULT '0',
  `upload_bytes` bigint NOT NULL DEFAULT '0',
  `download_bytes` bigint NOT NULL DEFAULT '0',
  `traffic_calc_mode` smallint NOT NULL DEFAULT '0',
  `protocol_multiplier_milli` bigint NOT NULL DEFAULT '1000',
  `used_bytes` bigint NOT NULL DEFAULT '0',
  `record_at` datetime(3) NOT NULL,
  `meta` text,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_traffic_node_report` (`node_id`,`report_id`),
  UNIQUE KEY `ux_traffic_node_nonce` (`node_id`,`nonce`),
  KEY `idx_traffic_user` (`user_id`),
  KEY `idx_traffic_node` (`node_id`),
  KEY `idx_traffic_time` (`record_at`),
  KEY `idx_traffic_records_subscription_id` (`subscription_id`),
  KEY `idx_traffic_protocol_endpoint` (`protocol_endpoint_id`),
  KEY `idx_traffic_records_flow` (`flow_id`),
  KEY `idx_traffic_records_event_type` (`event_type`),
  KEY `idx_traffic_records_history_cursor` (`record_at`,`id`),
  CONSTRAINT `fk_traffic_node` FOREIGN KEY (`node_id`) REFERENCES `nodes` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_traffic_protocol_endpoint` FOREIGN KEY (`protocol_endpoint_id`) REFERENCES `protocol_endpoints` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_traffic_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_api_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `token_hash` varchar(64) NOT NULL,
  `token_prefix` varchar(12) NOT NULL,
  `scopes` json DEFAULT NULL,
  `last_used_at` datetime(3) DEFAULT NULL,
  `revoked_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_api_tokens_hash` (`token_hash`),
  KEY `idx_user_api_tokens_user` (`user_id`),
  CONSTRAINT `fk_user_api_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `account_name` varchar(80) DEFAULT NULL,
  `email` varchar(128) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email_verified_at` datetime(3) DEFAULT NULL,
  `last_login_at` datetime(3) DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT '0',
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO system_configs
  (config_key, name, value, value_type, description, is_public, is_secret)
VALUES
  ('register_switch', '注册开关', 'true', 'bool', '是否允许注册', 1, 0),
  ('site_name', '站点名称', 'zboard', 'string', '用于展示站点名称的位置', 1, 0),
  ('site_desc', '站点描述', '', 'string', '用于展示需要站点描述的地方', 1, 0),
  ('site_logo', '站点 Logo', '', 'string', '网站的 Logo 地址', 1, 0),
  ('site_url', '站点网址', '', 'string', '当前站点的网址', 1, 0),
  ('subscribe_url', '订阅网址', '', 'string', '独立订阅地址；为空时由站点网址生成', 1, 0),
  ('task_email_enabled', '邮件任务开关', 'false', 'bool', '是否允许任务执行器发送邮件', 0, 0),
  ('smtp_host', 'SMTP 主机', '', 'string', '邮件服务器主机名', 0, 0),
  ('smtp_port', 'SMTP 端口', '587', 'int', '邮件服务器端口', 0, 0),
  ('smtp_username', 'SMTP 用户名', '', 'string', 'SMTP 登录用户名', 0, 0),
  ('smtp_password', 'SMTP 密码', '', 'string', 'SMTP 登录密码，使用凭证密钥加密保存', 0, 1),
  ('smtp_from', '发件地址', '', 'string', '邮件任务统一使用的发件邮箱', 0, 0),
  ('smtp_tls_mode', 'SMTP TLS 模式', 'starttls', 'string', '支持 starttls 或 implicit', 0, 0);

INSERT INTO subscription_templates
  (name, slug, description, renderer, customization, is_active, sort_order, revision, created_at, updated_at)
VALUES
  ('ZNet Sink', 'znet-sink', 'Zero 原生 JSON 配置；支持策略组、规则集和安全动态出站注入。', 'znet-sink', '{"version":2,"main_group":"main","policy_groups":[{"id":"main","name":"节点选择","type":"select","include_groups":["auto"],"default_group":"auto"},{"id":"auto","name":"自动选择","type":"urltest","probe_url":"https://www.gstatic.com/generate_204","interval":300,"tolerance":50}],"final":"group:main","rule_sets":[]}', 1, -300, 1, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
  ('Clash', 'clash', 'Mihomo / Clash Meta 原生 YAML 配置；支持策略组、规则集和安全动态节点注入。', 'clash', '{"version":2,"main_group":"main","policy_groups":[{"id":"main","name":"节点选择","type":"select","include_groups":["auto"],"default_group":"auto"},{"id":"auto","name":"自动选择","type":"urltest","probe_url":"https://www.gstatic.com/generate_204","interval":300,"tolerance":50}],"final":"group:main","rule_sets":[]}', 1, -290, 1, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)),
  ('sing-box', 'sing-box', 'sing-box 原生 JSON 配置；支持 selector、urltest、规则集和安全动态出站注入。', 'sing-box', '{"version":2,"main_group":"main","policy_groups":[{"id":"main","name":"节点选择","type":"select","include_groups":["auto"],"default_group":"auto"},{"id":"auto","name":"自动选择","type":"urltest","probe_url":"https://www.gstatic.com/generate_204","interval":300,"tolerance":50}],"final":"group:main","rule_sets":[]}', 1, -280, 1, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));

SET FOREIGN_KEY_CHECKS = 1;
