DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS traffic_records;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS nodes;
DROP TABLE IF EXISTS plans;
DROP TABLE IF EXISTS users;
