SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS
  registration_email_challenges,
  email_templates,
  subscription_template_rule_set_bindings,
  subscription_rule_sets,
  subscription_templates,
  certificate_protocol_endpoints,
  certificate_operations,
  provider_operations,
  managed_dns_records,
  provider_accounts,
  managed_certificates,
  flow_usages,
  protocol_credentials,
  protocol_deployments,
  node_kernel_states,
  node_operations,
  task_items,
  tasks,
  ticket_messages,
  tickets,
  quota_events,
  payment_events,
  traffic_records,
  subscription_members,
  subscription_tokens,
  orders,
  subscriptions,
  plan_skus,
  plans,
  node_group_endpoints,
  protocol_endpoints,
  node_groups,
  user_api_tokens,
  audit_logs,
  installations,
  system_configs,
  nodes,
  users;

SET FOREIGN_KEY_CHECKS = 1;
