CREATE TABLE IF NOT EXISTS plugin_installations (
 id VARCHAR(160) PRIMARY KEY, version_id VARCHAR(64) NOT NULL, name VARCHAR(160) NOT NULL,
 publisher VARCHAR(160) NOT NULL, state VARCHAR(24) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT FALSE,
 generation BIGINT UNSIGNED NOT NULL DEFAULT 1, config_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
 config_ciphertext LONGTEXT NOT NULL, last_error TEXT NOT NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS plugin_versions (
 id VARCHAR(64) PRIMARY KEY, plugin_id VARCHAR(160) NOT NULL, version VARCHAR(64) NOT NULL,
 digest VARCHAR(64) NOT NULL, publisher VARCHAR(160) NOT NULL, manifest LONGTEXT NOT NULL,
 created_at DATETIME(3) NOT NULL, INDEX idx_plugin_versions_plugin_id (plugin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS plugin_operations (
 id VARCHAR(64) PRIMARY KEY, plugin_id VARCHAR(160) NOT NULL, action VARCHAR(32) NOT NULL,
 state VARCHAR(24) NOT NULL, actor VARCHAR(191) NOT NULL, message TEXT NOT NULL,
 created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, INDEX idx_plugin_operations_plugin_id (plugin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS plugin_host_leases (
 id BIGINT UNSIGNED PRIMARY KEY, owner VARCHAR(64) NOT NULL, epoch BIGINT UNSIGNED NOT NULL, expires_at DATETIME(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
