CREATE TABLE IF NOT EXISTS plugin_authorizations (
 plugin_id VARCHAR(160) PRIMARY KEY, digest VARCHAR(64) NOT NULL, capabilities TEXT NOT NULL,
 native_trusted BOOLEAN NOT NULL DEFAULT FALSE, actor VARCHAR(191) NOT NULL, updated_at DATETIME(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS plugin_data (
 plugin_id VARCHAR(160) PRIMARY KEY, epoch BIGINT UNSIGNED NOT NULL DEFAULT 0, version BIGINT UNSIGNED NOT NULL DEFAULT 0,
 revision BIGINT UNSIGNED NOT NULL DEFAULT 0, ciphertext LONGTEXT NOT NULL, updated_at DATETIME(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS plugin_migrations (
 id VARCHAR(64) PRIMARY KEY, plugin_id VARCHAR(160) NOT NULL, epoch BIGINT UNSIGNED NOT NULL, version BIGINT UNSIGNED NOT NULL,
 checksum VARCHAR(64) NOT NULL, digest VARCHAR(64) NOT NULL, actor VARCHAR(191) NOT NULL, created_at DATETIME(3) NOT NULL,
 INDEX idx_plugin_migrations_plugin_id (plugin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
