package handler

import (
	"fmt"

	"github.com/zerodenet/zboard/backend/internal/model"
)

// ensureNodeTrafficReportCredential completes the node asset on first managed
// Zero bootstrap. The credential belongs to the compatibility/external
// /traffic/report path; managed Zero event accounting continues to use the
// Connector credential. An explicitly revoked traffic credential is preserved
// and is never silently regenerated by a later kernel reconcile.
func (h *handlers) ensureNodeTrafficReportCredential(node model.Node) error {
	if node.TrafficSecret != "" || node.TrafficSecretRevokedAt != nil {
		return nil
	}
	raw, prefix, err := newNodeReportSecret()
	if err != nil {
		return fmt.Errorf("generate traffic report credential: %w", err)
	}
	encrypted, err := h.credentialCipher.Encrypt(raw)
	if err != nil {
		return fmt.Errorf("encrypt traffic report credential: %w", err)
	}
	result := h.db.Model(&model.Node{}).
		Where("id = ? AND traffic_secret = '' AND traffic_secret_revoked_at IS NULL", node.ID).
		Updates(map[string]interface{}{
			"traffic_secret":            encrypted,
			"traffic_secret_prefix":     prefix,
			"traffic_secret_revoked_at": nil,
		})
	if result.Error != nil {
		return fmt.Errorf("persist traffic report credential: %w", result.Error)
	}
	return nil
}
