package handler

import (
	"context"
	"fmt"

	"github.com/zerodenet/zboard/backend/internal/capabilities/network"
	"github.com/zerodenet/zboard/backend/internal/model"
)

// prepareNodeTrafficReportCredential prepares the node asset on first managed
// Zero bootstrap. The credential belongs to the compatibility/external
// /traffic/report path; managed Zero event accounting continues to use the
// Connector credential. An explicitly revoked traffic credential is preserved
// and is never silently regenerated by a later kernel reconcile.
func (h *handlers) prepareNodeTrafficReportCredential(_ context.Context, node model.Node) (*network.KernelEncryptedCredential, error) {
	if node.TrafficSecret != "" || node.TrafficSecretRevokedAt != nil {
		return nil, nil
	}
	raw, prefix, err := newNodeReportSecret()
	if err != nil {
		return nil, fmt.Errorf("generate traffic report credential: %w", err)
	}
	encrypted, err := h.credentialCipher.Encrypt(raw)
	if err != nil {
		return nil, fmt.Errorf("encrypt traffic report credential: %w", err)
	}
	return &network.KernelEncryptedCredential{Ciphertext: encrypted, Prefix: prefix}, nil
}
